language: node_js
node_js:
  - "6.9"
sudo: required
env:
  global:
    - AWS_ACCESS_KEY_ID=AKIAJ5RHRO2T2SRL2J4A
    - AWS_DEFAULT_REGION=us-west-2
    - secure: "A6Pe2Pjy59juWfhU1V5DNtcr6PmpvEm9t5Dw4i9t700zpF0tsnyq3X+m8cgi03Uy6cob7d81SACvJTh9OrUBw4tCh3YfSREeznjMPvO1CX0xvEcq6CB7E4wxxo22xE3knRkfCiF0i9oh6//ELyv2V9ofHIQazQKF57Nyr4CjaZ1oP6zQ649BK7rMCMflVclBAO603G0013EP+euote7PLjKHsWf98iaD9rcr1Gs66Zko3SL/yRwxC6wriZtU61LrXlEMKCg4w6HrN/M98CJJTsfFODkPGqtvq/jtywbqJnjvmAq+P/Gp7X4Cj9KFmOs5NBlg89o/IrnTq5cXUHrUd/UTC1dCXnJ+G6EzOOwqa52OwuWB1tEIS0TrWjFSLRalJzEBz91xsOsp3PcvpWtGJIX2NusZTPveEJEfCqwZtb+u5kGq+JrcmTzDHmTk/UIy8TMdXnWQqBCe0ce9gx5otJX0FjokC10EOWDfSACaK6oYqZflZkuYWPK3txCRMSdaEEU9AiLZfl263uK/ZLM8I+M9MLGMOMVH8ZPV3ZFvE7wru+jeP29e9FhzpVW6Qe6JlulFK0uhs96GUa9aQU86fwTfR5cdnh/NPRExVBvqRg2sPUeYIFdN4c2nH39ncuFCBxr5SaBzzVEI9F6oVEjD2j6f41CNOyu+9ftjGMflbNI="
before_install:
  - sudo pip install awscli
  - ./ci/setup.sh
script:
  - npm install
  - ./ci/lint.sh
  - ./ci/deploy.sh
  - ./ci/test.sh
after_script:
  - ./ci/teardown.sh
