language: node_js
node_js:
  - "6.9"
sudo: required
env:
  - AWS_ACCESS_KEY_ID=foo AWS_SECRET_ACCESS_KEY=bar AWS_DEFAULT_REGION=us-west-2
before_install:
  - sudo pip install awscli
  - aws help
  - ssh-keygen -t rsa -C 'user0001@slalom.com' -b 4096 -f id_rsa -N ''
  - aws iam upload-ssh-public-key --user-name User0001 --ssh-public-key-body $(cat id_rsa.pub)
install:
  - npm install
script:
  - npm run lint
  - node app &
  - npm run test
