language: node_js
node_js:
  - "6.9"
env:
  - AWS_ACCESS_KEY_ID=foo
  - AWS_SECRET_ACCESS_KEY=bar
  - AWS_DEFAULT_REGION=us-west-2
before_install:
  - pip install awscli
  - aws help
install:
  - npm install
script:
  - npm run lint
  - node app &
  - npm run test
